Milestone #5 - Display Joined Missions and Reserved Rockets in My Profile
vicmaburrito/Space-Travelers-Hub pull request #40
Opened 2022-01-26 22:20 UTC by Anjacodes

In this milestone, we worked on: 

* #3 - Render a list of all reserved rockets on the "My profile" page.
* #2 - Render a list of all joined missions on the "My profile" page.
* Added Styling using Bootstrap CSS

2022-01-26 23:32 UTC, bimbolabuari requested changes
Hi Team, 

You have done a good job so far 🚀  

## Highlights 🎉 

- Install React-Redux, Redux Logger, and React Router.
- `useSelector()` is used to get a state slice corresponding to routes
- No Linter error
- The My Profile section displays all reserved rockets and space missions.
- The Missions section displays a list of current missions along with their brief description and participation status. There is also a button next to each mission that allows users to join the selected mission or leave the mission the user joined earlier
- The Rockets section displays a list of all available SpaceX rockets. Users can book each rocket by clicking the reservation button or cancel the previously made booking

There are some issues that you still need to work on to go to the next project but you are almost there! 🎉 

## Required Changes ♻️
- [ ] As required, Kindly add unit tests with React Testing Library and Jest 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

--------


_Reviewed by  @bimbolabuari_

2022-01-26 23:32 UTC, bimbolabuari commented on README.md
> +<a href="https://affectionate-mirzakhani-76e566.netlify.app/" rel="noopener noreferrer">Live Demo Link</a> -->
Let's remove other project information and description from the readme file to make it look cleaner and more professional ✊

2022-01-26 23:32 UTC, bimbolabuari commented on README.md
> +$ cd bookstore `
Let's remove other project information and description from the readme file to make it look cleaner and more professional ✊

Kindly check for other occurrences 🙂

2022-01-26 23:32 UTC, bimbolabuari commented on src/components/MyProfile/MyProfile.js
> +      </div>
Let's add the `reserved` button to indicate reserved rockets as it's in the required wireframe 👍 

> Required Rocket wireframe
![Screenshot (381)](https://user-images.githubusercontent.com/66112760/151264420-2e09467b-0675-4e40-93fe-a7fa559fb217.png)


> Your Rocket Screenshot
![Screenshot (380)](https://user-images.githubusercontent.com/66112760/151264441-b5fe12b3-52a7-49c4-9ca2-d6a9c9407f05.png)

2022-01-27 15:55 UTC, Anjacodes commented on README.md
> +<a href="https://affectionate-mirzakhani-76e566.netlify.app/" rel="noopener noreferrer">Live Demo Link</a> -->
Hi @bimbolabuari, thank you for your feedback and for being attentive. All your suggestions have been implemented! 🙏

2022-01-27 16:12 UTC, eri8-9 approved these changes
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

- Well done!

![Felix](https://media.giphy.com/media/hlQeY3PbhH3i/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-27 16:14 UTC, merged